/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E_4BSEN;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Dashboard_guru extends javax.swing.JFrame {
    
    public String namaUser;
    
    public void tampilkanStatistik() {
        Connection conn = koneksi.getKoneksi();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Gagal terhubung ke database. Statistik tidak dapat ditampilkan.", "Error Koneksi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            String sqlSiswa = "SELECT COUNT(*) as total FROM siswa";
            PreparedStatement psSiswa = conn.prepareStatement(sqlSiswa);
            ResultSet rsSiswa = psSiswa.executeQuery();
            if (rsSiswa.next()) {
                lbl_jumlah_siswa.setText(rsSiswa.getString("total"));
            }

            String sqlAbsen = "SELECT COUNT(*) as total FROM absensi";
            PreparedStatement psAbsen = conn.prepareStatement(sqlAbsen);
            ResultSet rsAbsen = psAbsen.executeQuery();
            if (rsAbsen.next()) {
                lbl_jumlah_absensi.setText(rsAbsen.getString("total"));
            }

            String sqlRata = "SELECT (SUM(CASE WHEN status='Hadir' THEN 1 ELSE 0 END) * 100.0 / COUNT(*)) as rata " +
                             "FROM detail_absensi";
            PreparedStatement psRata = conn.prepareStatement(sqlRata);
            ResultSet rsRata = psRata.executeQuery();
            if (rsRata.next()) {
                double hasil = rsRata.getDouble("rata");
                lbl_ratarata.setText(String.format("%.1f%%", hasil));
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil statistik: " + e.getMessage());
        } finally {
            try {
                if (conn != null && !conn.isClosed()) {
                    // Kita tidak menutup koneksi di sini jika koneksi bersifat singleton/static di class koneksi
                    // Tapi jika getKoneksi() selalu membuat baru, maka harus ditutup.
                    // Berdasarkan koneksi.java, itu static, jadi jangan ditutup di sini.
                }
            } catch (SQLException ex) {
                logger.log(java.util.logging.Level.SEVERE, null, ex);
            }
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Dashboard_guru.class.getName());

    /**
     * Creates new form Dashboard_guru
     */
    public Dashboard_guru() {
        initComponents();
        
        panel_borderradius.putClientProperty("FlatLaf.style", "arc: 30; background: #ffffff");
        panel_borderradius1.putClientProperty("FlatLaf.style", "arc: 30; background: #ffffff");
        panel_borderradius2.putClientProperty("FlatLaf.style", "arc: 30; background: #ffffff");
        
        panel_bulat.putClientProperty("FlatLaf.style", "arc: 30; background: rgb(195, 199, 196)");
        panel_bulat1.putClientProperty("FlatLaf.style", "arc: 30; background: rgb(195, 199, 196)");
        panel_bulat2.putClientProperty("FlatLaf.style", "arc: 30; background: rgb(195, 199, 196)");
        
        pnl_datasiswa.putClientProperty("FlatLaf.style", "arc: 30;");
        pnl_inputabsensi.putClientProperty("FlatLaf.style", "arc: 30;");
        pnl_rekapkehadiran.putClientProperty("FlatLaf.style", "arc: 30;");
        
        lbl_username.setText(namaUser);
        
        tampilkanStatistik();
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        jDialog1 = new javax.swing.JDialog();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_username = new javax.swing.JLabel();
        logout = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        panel_borderradius = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbl_jumlah_siswa = new javax.swing.JLabel();
        panel_borderradius1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbl_jumlah_absensi = new javax.swing.JLabel();
        panel_borderradius2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lbl_ratarata = new javax.swing.JLabel();
        pnl_inputabsensi = new javax.swing.JPanel();
        btn_inputabsensi = new javax.swing.JButton();
        panel_bulat1 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pnl_rekapkehadiran = new javax.swing.JPanel();
        btn_rekapkehadiran = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        panel_bulat2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        pnl_datasiswa = new javax.swing.JPanel();
        btn_datasiswa = new javax.swing.JButton();
        panel_bulat = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(247, 250, 252));
        jPanel1.setOpaque(false);

        jPanel2.setBackground(new java.awt.Color(30, 41, 59));

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E - 4BSENSI");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Selamat datang,");

        lbl_username.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        lbl_username.setForeground(new java.awt.Color(255, 255, 255));
        lbl_username.setText("User");

        logout.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_username)
                .addGap(18, 18, 18)
                .addComponent(logout)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(lbl_username)
                    .addComponent(logout))
                .addGap(10, 10, 10))
        );

        jLabel5.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        jLabel5.setText("Dashboard Utama");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(88, 91, 94));
        jLabel6.setText("Kelola data siswa dan kehadiran akademik.");

        panel_borderradius.setBackground(new java.awt.Color(255, 255, 255));
        panel_borderradius.setPreferredSize(new java.awt.Dimension(405, 114));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(88, 91, 94));
        jLabel7.setText("Total Siswa");

        lbl_jumlah_siswa.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_jumlah_siswa.setText("Jumlah Siswa");

        javax.swing.GroupLayout panel_borderradiusLayout = new javax.swing.GroupLayout(panel_borderradius);
        panel_borderradius.setLayout(panel_borderradiusLayout);
        panel_borderradiusLayout.setHorizontalGroup(
            panel_borderradiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_borderradiusLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_borderradiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(lbl_jumlah_siswa))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_borderradiusLayout.setVerticalGroup(
            panel_borderradiusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_borderradiusLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_jumlah_siswa)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        panel_borderradius1.setBackground(new java.awt.Color(255, 255, 255));
        panel_borderradius1.setPreferredSize(new java.awt.Dimension(405, 114));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(88, 91, 94));
        jLabel9.setText("Absensi Minggu Ini");

        lbl_jumlah_absensi.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_jumlah_absensi.setText("Jumlah Absensi");

        javax.swing.GroupLayout panel_borderradius1Layout = new javax.swing.GroupLayout(panel_borderradius1);
        panel_borderradius1.setLayout(panel_borderradius1Layout);
        panel_borderradius1Layout.setHorizontalGroup(
            panel_borderradius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_borderradius1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_borderradius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lbl_jumlah_absensi))
                .addContainerGap(134, Short.MAX_VALUE))
        );
        panel_borderradius1Layout.setVerticalGroup(
            panel_borderradius1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_borderradius1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(lbl_jumlah_absensi)
                .addGap(11, 11, 11))
        );

        panel_borderradius2.setBackground(new java.awt.Color(255, 255, 255));
        panel_borderradius2.setPreferredSize(new java.awt.Dimension(405, 114));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(88, 91, 94));
        jLabel11.setText("Rata-rata Kehadiran");

        lbl_ratarata.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lbl_ratarata.setText("Rata-rata");

        javax.swing.GroupLayout panel_borderradius2Layout = new javax.swing.GroupLayout(panel_borderradius2);
        panel_borderradius2.setLayout(panel_borderradius2Layout);
        panel_borderradius2Layout.setHorizontalGroup(
            panel_borderradius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_borderradius2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(panel_borderradius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(lbl_ratarata))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        panel_borderradius2Layout.setVerticalGroup(
            panel_borderradius2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_borderradius2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ratarata)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pnl_inputabsensi.setBackground(new java.awt.Color(255, 255, 255));
        pnl_inputabsensi.setBorder(new javax.swing.border.MatteBorder(null));
        pnl_inputabsensi.setPreferredSize(new java.awt.Dimension(405, 170));

        btn_inputabsensi.setBackground(new java.awt.Color(30, 41, 59));
        btn_inputabsensi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_inputabsensi.setForeground(new java.awt.Color(255, 255, 255));
        btn_inputabsensi.setText("Buka");
        btn_inputabsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputabsensiActionPerformed(evt);
            }
        });

        panel_bulat1.setBackground(new java.awt.Color(195, 199, 196));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_4BSEN/src/add_notes_24dp_0, 0, 0_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout panel_bulat1Layout = new javax.swing.GroupLayout(panel_bulat1);
        panel_bulat1.setLayout(panel_bulat1Layout);
        panel_bulat1Layout.setHorizontalGroup(
            panel_bulat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bulat1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_bulat1Layout.setVerticalGroup(
            panel_bulat1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bulat1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel17.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel17.setText("Input Absensi");

        jLabel18.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(88, 91, 94));
        jLabel18.setText("Masukkan Data Kehadiran");

        javax.swing.GroupLayout pnl_inputabsensiLayout = new javax.swing.GroupLayout(pnl_inputabsensi);
        pnl_inputabsensi.setLayout(pnl_inputabsensiLayout);
        pnl_inputabsensiLayout.setHorizontalGroup(
            pnl_inputabsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_inputabsensiLayout.createSequentialGroup()
                .addContainerGap(117, Short.MAX_VALUE)
                .addGroup(pnl_inputabsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_inputabsensiLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_inputabsensiLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(157, 157, 157))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_inputabsensiLayout.createSequentialGroup()
                        .addComponent(panel_bulat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))))
            .addGroup(pnl_inputabsensiLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btn_inputabsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnl_inputabsensiLayout.setVerticalGroup(
            pnl_inputabsensiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_inputabsensiLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panel_bulat1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_inputabsensi, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_rekapkehadiran.setBackground(new java.awt.Color(255, 255, 255));
        pnl_rekapkehadiran.setBorder(new javax.swing.border.MatteBorder(null));
        pnl_rekapkehadiran.setPreferredSize(new java.awt.Dimension(405, 170));

        btn_rekapkehadiran.setBackground(new java.awt.Color(30, 41, 59));
        btn_rekapkehadiran.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_rekapkehadiran.setForeground(new java.awt.Color(255, 255, 255));
        btn_rekapkehadiran.setText("Buka");
        btn_rekapkehadiran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rekapkehadiranActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel20.setText("Rekap Kehadiran");

        jLabel21.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(88, 91, 94));
        jLabel21.setText("Lihat seluruh rekapan absensi");

        panel_bulat2.setBackground(new java.awt.Color(195, 199, 196));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_4BSEN/src/folder_eye_24dp_0, 0, 0_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout panel_bulat2Layout = new javax.swing.GroupLayout(panel_bulat2);
        panel_bulat2.setLayout(panel_bulat2Layout);
        panel_bulat2Layout.setHorizontalGroup(
            panel_bulat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bulat2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_bulat2Layout.setVerticalGroup(
            panel_bulat2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bulat2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_rekapkehadiranLayout = new javax.swing.GroupLayout(pnl_rekapkehadiran);
        pnl_rekapkehadiran.setLayout(pnl_rekapkehadiranLayout);
        pnl_rekapkehadiranLayout.setHorizontalGroup(
            pnl_rekapkehadiranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_rekapkehadiranLayout.createSequentialGroup()
                .addGap(0, 116, Short.MAX_VALUE)
                .addGroup(pnl_rekapkehadiranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_rekapkehadiranLayout.createSequentialGroup()
                        .addComponent(panel_bulat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(172, 172, 172))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_rekapkehadiranLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(95, 95, 95))))
            .addGroup(pnl_rekapkehadiranLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_rekapkehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnl_rekapkehadiranLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jLabel20))
        );
        pnl_rekapkehadiranLayout.setVerticalGroup(
            pnl_rekapkehadiranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_rekapkehadiranLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel_bulat2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_rekapkehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pnl_datasiswa.setBackground(new java.awt.Color(255, 255, 255));
        pnl_datasiswa.setBorder(new javax.swing.border.MatteBorder(null));
        pnl_datasiswa.setPreferredSize(new java.awt.Dimension(405, 170));

        btn_datasiswa.setBackground(new java.awt.Color(30, 41, 59));
        btn_datasiswa.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_datasiswa.setForeground(new java.awt.Color(255, 255, 255));
        btn_datasiswa.setText("Buka");
        btn_datasiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_datasiswaActionPerformed(evt);
            }
        });

        panel_bulat.setBackground(new java.awt.Color(195, 199, 196));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_4BSEN/src/search_24dp_0, 0, 0_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N

        javax.swing.GroupLayout panel_bulatLayout = new javax.swing.GroupLayout(panel_bulat);
        panel_bulat.setLayout(panel_bulatLayout);
        panel_bulatLayout.setHorizontalGroup(
            panel_bulatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bulatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_bulatLayout.setVerticalGroup(
            panel_bulatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_bulatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel14.setText("Data Siswa");

        jLabel15.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(88, 91, 94));
        jLabel15.setText("Cari dan kelola informasi siswa");

        javax.swing.GroupLayout pnl_datasiswaLayout = new javax.swing.GroupLayout(pnl_datasiswa);
        pnl_datasiswa.setLayout(pnl_datasiswaLayout);
        pnl_datasiswaLayout.setHorizontalGroup(
            pnl_datasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_datasiswaLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(btn_datasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)
                .addGap(48, 48, 48))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datasiswaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_datasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datasiswaLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datasiswaLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(165, 165, 165))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datasiswaLayout.createSequentialGroup()
                        .addComponent(panel_bulat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))))
        );
        pnl_datasiswaLayout.setVerticalGroup(
            pnl_datasiswaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_datasiswaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(panel_bulat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_datasiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        jLabel13.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel13.setText("Quick Action");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnl_datasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE)
                            .addComponent(panel_borderradius, javax.swing.GroupLayout.DEFAULT_SIZE, 413, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_inputabsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_borderradius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_rekapkehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_borderradius2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(panel_borderradius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_borderradius2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(panel_borderradius1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(70, 70, 70)
                .addComponent(jLabel13)
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pnl_inputabsensi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(pnl_datasiswa, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                    .addComponent(pnl_rekapkehadiran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE))
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void btn_datasiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_datasiswaActionPerformed
        new Data_siswa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_datasiswaActionPerformed

    private void btn_inputabsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputabsensiActionPerformed
        new input_absensi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_inputabsensiActionPerformed

    private void btn_rekapkehadiranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rekapkehadiranActionPerformed
        new Rekap_absensi().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_rekapkehadiranActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Dashboard_guru().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_datasiswa;
    private javax.swing.JButton btn_inputabsensi;
    private javax.swing.JButton btn_rekapkehadiran;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JLabel lbl_jumlah_absensi;
    private javax.swing.JLabel lbl_jumlah_siswa;
    private javax.swing.JLabel lbl_ratarata;
    private javax.swing.JLabel lbl_username;
    private javax.swing.JLabel logout;
    private javax.swing.JPanel panel_borderradius;
    private javax.swing.JPanel panel_borderradius1;
    private javax.swing.JPanel panel_borderradius2;
    private javax.swing.JPanel panel_bulat;
    private javax.swing.JPanel panel_bulat1;
    private javax.swing.JPanel panel_bulat2;
    private javax.swing.JPanel pnl_datasiswa;
    private javax.swing.JPanel pnl_inputabsensi;
    private javax.swing.JPanel pnl_rekapkehadiran;
    // End of variables declaration//GEN-END:variables
}
