/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E_4BSEN;

import java.sql.*;
import javax.swing.table.*;
import javax.swing.JOptionPane;
import javax.swing.DefaultCellEditor;
import javax.swing.JLabel;
/**
 *
 * @author DELL
 */
public class Data_siswa extends javax.swing.JFrame {
    
    public void loadDataSiswa() {
        DefaultTableModel model = (DefaultTableModel) tbl_siswa.getModel();
        model.setRowCount(0);

        String sql = "SELECT s.nis, s.nama_siswa, s.jenis_kelamin, s.alamat, k.nama_kelas " +
                     "FROM siswa s JOIN kelas k ON s.id_kelas = k.id_kelas";

        Connection conn = koneksi.getKoneksi();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Gagal terhubung ke database!", "Error Koneksi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nis"),
                    rs.getString("nama_siswa"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("alamat"),
                    rs.getString("nama_kelas")
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal ambil data: " + e.getMessage());
        }
    }
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Data_siswa.class.getName());

    /**
     * Creates new form Data_siswa
     */
    public Data_siswa() {
        initComponents();
        
        loadDataSiswa();

        tbl_siswa.getTableHeader().setReorderingAllowed(false);
        tbl_siswa.setShowVerticalLines(false);
        tbl_siswa.setShowHorizontalLines(true);
        tbl_siswa.setIntercellSpacing(new java.awt.Dimension(0, 1));
        tbl_siswa.setRowHeight(40);
        
        scrollPane.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        scrollPane.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder());

        tbl_siswa.getTableHeader().putClientProperty("FlatLaf.style", 
            "font: bold;" + 
            "background: #f8f9fa; " +
            "separatorColor: #f8f9fa; " + 
            "height: 40;" +
            "RoundRect: 30"
        );

        // Styling Body Tabel
        tbl_siswa.putClientProperty("FlatLaf.style", 
            "selectionBackground: #e9ecef; " + 
            "selectionForeground: #212529; " + 
            "showHorizontalLines: true; " +
            "horizontalLineColor: #f1f3f5" 
        );
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        
        tbl_siswa.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        tbl_siswa.getColumnModel().getColumn(1).setCellRenderer(centerRenderer);
        tbl_siswa.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        tbl_siswa.getColumnModel().getColumn(3).setCellRenderer(centerRenderer);
        tbl_siswa.getColumnModel().getColumn(4).setCellRenderer(centerRenderer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        scrollPane = new javax.swing.JScrollPane();
        tbl_siswa = new javax.swing.JTable();
        btn_tambah_siswa_baru = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Data Seluruh Siswa");

        tbl_siswa.setBackground(new java.awt.Color(247, 249, 250));
        tbl_siswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NIS", "Nama Siswa", "Jenis kelamin", "alamat", "id kelas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_siswa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbl_siswa.setEditingColumn(0);
        tbl_siswa.setEditingRow(0);
        tbl_siswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_siswaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tbl_siswaMouseEntered(evt);
            }
        });
        scrollPane.setViewportView(tbl_siswa);

        btn_tambah_siswa_baru.setBackground(new java.awt.Color(26, 135, 84));
        btn_tambah_siswa_baru.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_tambah_siswa_baru.setForeground(new java.awt.Color(255, 255, 255));
        btn_tambah_siswa_baru.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_4BSEN/src/add_2_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_tambah_siswa_baru.setText("Tambah Siswa Baru");
        btn_tambah_siswa_baru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_siswa_baruActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(30, 41, 59));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E - 4BSENSI");

        back.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Kembali ke Dashboard");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(35, 35, 35))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(back))
                .addGap(10, 10, 10))
        );

        btn_edit.setBackground(new java.awt.Color(86, 130, 232));
        btn_edit.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_4BSEN/src/edit_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_edit.setText("Edit");
        btn_edit.setEnabled(false);
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(255, 0, 5));
        btn_delete.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/E_4BSEN/src/delete_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24.png"))); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.setEnabled(false);
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 956, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_delete)
                        .addGap(18, 18, 18)
                        .addComponent(btn_edit)
                        .addGap(18, 18, 18)
                        .addComponent(btn_tambah_siswa_baru)))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_tambah_siswa_baru)
                        .addComponent(btn_edit)
                        .addComponent(btn_delete)))
                .addGap(18, 18, 18)
                .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tambah_siswa_baruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_siswa_baruActionPerformed
        new tambah_siswa_baru().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_tambah_siswa_baruActionPerformed

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new Dashboard_guru().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void tbl_siswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_siswaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_siswaMouseEntered

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        int row = tbl_siswa.getSelectedRow();
        if (row != -1) {
            // 1. Ambil semua data dari baris tabel
            String nis = tbl_siswa.getValueAt(row, 0).toString();
            String nama = tbl_siswa.getValueAt(row, 1).toString();
            String jk = tbl_siswa.getValueAt(row, 2).toString();
            String alamat = tbl_siswa.getValueAt(row, 3).toString();
            String kelas = tbl_siswa.getValueAt(row, 4).toString();

            // 2. Buka form tambah_siswa (tapi kirim datanya)
            tambah_siswa_baru formEdit = new tambah_siswa_baru();
            formEdit.siapkanEdit(nis, nama, jk, kelas, alamat); // Buat fungsi ini di form tambah_siswa
            formEdit.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        int row = tbl_siswa.getSelectedRow();
        if (row != -1) {
            String nis = tbl_siswa.getValueAt(row, 0).toString();
            int confirm = JOptionPane.showConfirmDialog(this, "Yakin ingin menghapus siswa dengan NIS: " + nis + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                try (Connection conn = koneksi.getKoneksi()) {
                    String sql = "DELETE FROM siswa WHERE nis = ?";
                    PreparedStatement ps = conn.prepareStatement(sql);
                    ps.setString(1, nis);

                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus!");

                    loadDataSiswa(); // Refresh tabel
                    btn_delete.setEnabled(false);
                    btn_edit.setEnabled(false);

                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
                }
            }
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void tbl_siswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_siswaMouseClicked
        int row = tbl_siswa.getSelectedRow();
        if (row != -1) {
            // Aktifkan tombol saat baris diklik
            btn_edit.setEnabled(true);
            btn_delete.setEnabled(true);

            // Ambil data dari baris yang diklik untuk bahan edit/hapus
            String nis = tbl_siswa.getValueAt(row, 0).toString();
            // Simpan nis ini ke variabel global jika diperlukan
        }
    }//GEN-LAST:event_tbl_siswaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Data_siswa().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_tambah_siswa_baru;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tbl_siswa;
    // End of variables declaration//GEN-END:variables
}
