/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E_4BSEN;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JLabel;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import java.time.format.DateTimeFormatter;
import java.time.LocalDate;
import java.sql.Statement;

/**
 *
 * @author DELL
 */
public class input_absensi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(input_absensi.class.getName());

    /**
     * Creates new form input_absensi
     */
    public input_absensi() {
        initComponents();
        
        pnl_pilihkelas.putClientProperty("FlatLaf.style", "arc: 30;");
        pnl_table.putClientProperty("FlatLaf.style", "arc: 30;");
        
        LocalDate hariIni = LocalDate.now();
        DateTimeFormatter formatTgl = DateTimeFormatter.ofPattern("yyyy-MM-dd");
        tf_tanggal.setText(hariIni.format(formatTgl));
        tf_tanggal.setEditable(false);
        
        tf_pertemuan.addKeyListener(new java.awt.event.KeyAdapter() {
        @Override
        public void keyTyped(java.awt.event.KeyEvent evt) {
        char c = evt.getKeyChar();
       
        if (!(Character.isDigit(c) || (c == java.awt.event.KeyEvent.VK_BACK_SPACE) || (c == java.awt.event.KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }
});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_pilihkelas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cb_kelas = new javax.swing.JComboBox<>();
        btn_bukadaftar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        pnl_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_absensi = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tf_tanggal = new javax.swing.JTextField();
        tf_pertemuan = new javax.swing.JTextField();
        tf_simpandata = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(242, 246, 250));

        pnl_pilihkelas.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Pilih Kelas");

        cb_kelas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cb_kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XI RPL 1", "XI RPL 2", "XI RPL 3" }));

        btn_bukadaftar.setBackground(new java.awt.Color(13, 109, 252));
        btn_bukadaftar.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        btn_bukadaftar.setForeground(new java.awt.Color(255, 255, 255));
        btn_bukadaftar.setText("Buka Daftar");
        btn_bukadaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bukadaftarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_pilihkelasLayout = new javax.swing.GroupLayout(pnl_pilihkelas);
        pnl_pilihkelas.setLayout(pnl_pilihkelasLayout);
        pnl_pilihkelasLayout.setHorizontalGroup(
            pnl_pilihkelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pilihkelasLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnl_pilihkelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_pilihkelasLayout.createSequentialGroup()
                        .addComponent(cb_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btn_bukadaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(414, Short.MAX_VALUE))
        );
        pnl_pilihkelasLayout.setVerticalGroup(
            pnl_pilihkelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_pilihkelasLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(pnl_pilihkelasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_bukadaftar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(30, 41, 59));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E - 4BSENSI");

        back.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        back.setForeground(new java.awt.Color(255, 255, 255));
        back.setText("Kembali ke Dashboard");
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(back)
                .addGap(35, 35, 35))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(back))
                .addGap(10, 10, 10))
        );

        pnl_table.setBackground(new java.awt.Color(255, 255, 255));

        table_absensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIS", "Nama Lengkap", "Status Kehadiran"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_absensi);

        jLabel3.setText("Tanggal Absensi");

        jLabel4.setText("Pertemuan Ke-");

        tf_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_tanggalActionPerformed(evt);
            }
        });

        tf_pertemuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_pertemuanActionPerformed(evt);
            }
        });

        tf_simpandata.setBackground(new java.awt.Color(26, 135, 84));
        tf_simpandata.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        tf_simpandata.setForeground(new java.awt.Color(255, 255, 255));
        tf_simpandata.setText("Simpan Data Absensi Ini");
        tf_simpandata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_simpandataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_tableLayout = new javax.swing.GroupLayout(pnl_table);
        pnl_table.setLayout(pnl_tableLayout);
        pnl_tableLayout.setHorizontalGroup(
            pnl_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tf_simpandata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnl_tableLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(pnl_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_tableLayout.createSequentialGroup()
                        .addGroup(pnl_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(tf_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(75, 75, 75)
                        .addGroup(pnl_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tf_pertemuan, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        pnl_tableLayout.setVerticalGroup(
            pnl_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_tableLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnl_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnl_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_pertemuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(tf_simpandata, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnl_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(pnl_pilihkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnl_pilihkelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(pnl_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMouseClicked
        new Dashboard_guru().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_backMouseClicked

    private void btn_bukadaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bukadaftarActionPerformed
        // 1. Ambil ID Kelas (Misal abang simpan ID-nya di ComboBox atau mapping)
        String namaKelas = cb_kelas.getSelectedItem().toString();

        String sql = "SELECT nis, nama_siswa FROM siswa " +
                     "JOIN kelas ON siswa.id_kelas = kelas.id_kelas " +
                     "WHERE kelas.nama_kelas = ?";

        DefaultTableModel model = (DefaultTableModel) table_absensi.getModel();
        model.setRowCount(0); // Reset tabel biar nggak numpuk

        Connection conn = koneksi.getKoneksi();
        if (conn == null) {
            JOptionPane.showMessageDialog(this, "Gagal terhubung ke database!", "Error Koneksi", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try (PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, namaKelas);
            ResultSet rs = ps.executeQuery();

            while (rs.next()) {
                // Masukkan NIS, Nama, dan default status (misal "Hadir")
                model.addRow(new Object[]{
                    rs.getString("nis"),
                    rs.getString("nama_siswa"),
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);

        table_absensi.getColumnModel().getColumn(0).setCellRenderer(centerRenderer);
        table_absensi.getColumnModel().getColumn(2).setCellRenderer(centerRenderer);
        
        String[] status = {"Hadir", "Izin", "Sakit", "Alpa"};
        JComboBox comboBox = new JComboBox(status);

        // 2. Pasang ComboBox tersebut ke kolom index 2 (Status Kehadiran)
        table_absensi.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(comboBox));
    }//GEN-LAST:event_btn_bukadaftarActionPerformed

    private void tf_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_tanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_tanggalActionPerformed

    private void tf_pertemuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_pertemuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_pertemuanActionPerformed

    private void tf_simpandataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_simpandataActionPerformed

            DefaultTableModel model = (DefaultTableModel) table_absensi.getModel();
                if (model.getRowCount() == 0) {
                    JOptionPane.showMessageDialog(this, "Tabel kosong!");
                    return;
                }

                String tgl = tf_tanggal.getText();
                String pertemuan = tf_pertemuan.getText();
                String namaKelas = cb_kelas.getSelectedItem().toString();

                Connection conn = koneksi.getKoneksi();
                if (conn == null) {
                    JOptionPane.showMessageDialog(this, "Gagal terhubung ke database!", "Error Koneksi", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                try {
                    conn.setAutoCommit(false); 

                    int idKelas = 0;
                    String sqlKelas = "SELECT id_kelas FROM kelas WHERE nama_kelas = ?";
                    PreparedStatement psKelas = conn.prepareStatement(sqlKelas);
                    psKelas.setString(1, namaKelas);
                    ResultSet rsK = psKelas.executeQuery();
                    if(rsK.next()) idKelas = rsK.getInt("id_kelas");

                    String sqlAbsen = "INSERT INTO absensi (id_jadwal, id_kelas, tanggal, pertemuan_ke) VALUES (1, ?, ?, ?)";
                    PreparedStatement psAbsen = conn.prepareStatement(sqlAbsen, Statement.RETURN_GENERATED_KEYS);
                    psAbsen.setInt(1, idKelas);
                    psAbsen.setString(2, tgl);
                    psAbsen.setString(3, pertemuan);
                    psAbsen.executeUpdate();
                    
                    ResultSet rsKey = psAbsen.getGeneratedKeys();
                    int idAbsenBaru = 0;
                    if (rsKey.next()) idAbsenBaru = rsKey.getInt(1);

                    String sqlDetail = "INSERT INTO detail_absensi (id_absensi, id_siswa, status) VALUES (?, (SELECT id_siswa FROM siswa WHERE nis = ?), ?)";
                    PreparedStatement psDetail = conn.prepareStatement(sqlDetail);

                    for (int i = 0; i < model.getRowCount(); i++) {
                        psDetail.setInt(1, idAbsenBaru);
                        psDetail.setString(2, model.getValueAt(i, 0).toString()); // NIS
                        psDetail.setString(3, model.getValueAt(i, 2).toString()); // Status (Hadir/Izin/dll)
                        psDetail.addBatch();
                    }
                    psDetail.executeBatch();
                    conn.commit();

                    JOptionPane.showMessageDialog(this, "Absensi berhasil disimpan!");
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(this, "Gagal simpan: " + e.getMessage());
            }
        
        
        if (tf_pertemuan.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pertemuan ke berapa?");
            tf_pertemuan.requestFocus();
            return;
        }
    }//GEN-LAST:event_tf_simpandataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new input_absensi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JButton btn_bukadaftar;
    private javax.swing.JComboBox<String> cb_kelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_pilihkelas;
    private javax.swing.JPanel pnl_table;
    private javax.swing.JTable table_absensi;
    private javax.swing.JTextField tf_pertemuan;
    private javax.swing.JButton tf_simpandata;
    private javax.swing.JTextField tf_tanggal;
    // End of variables declaration//GEN-END:variables
}
