/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E_4BSEN;

import com.formdev.flatlaf.FlatClientProperties;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import java.sql.Connection;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Rekap_absensi extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Rekap_absensi.class.getName());
    
    /**
     * Creates new form Laporan_absensi
     */
    public Rekap_absensi() {
        initComponents();
        
        loadDataRekap();
        
        pnl_table.putClientProperty("FlatLaf.style", "arc: 30;");
        
        tbl_rekap.getTableHeader().putClientProperty("FlatLaf.style", 
        "background: #212529;" +
        "foreground: #ffffff;" +
        "separatorColor: #212529;" +
        "font: bold +1"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        pnl_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_rekap = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(247, 249, 250));

        jButton1.setBackground(new java.awt.Color(107, 117, 125));
        jButton1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel1.setText("Detail Absensi");

        pnl_table.setBackground(new java.awt.Color(255, 255, 255));

        tbl_rekap.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id_absensi", "Tanggal", "Ringkasan Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_rekap.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_rekapMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_rekap);

        javax.swing.GroupLayout pnl_tableLayout = new javax.swing.GroupLayout(pnl_table);
        pnl_table.setLayout(pnl_tableLayout);
        pnl_tableLayout.setHorizontalGroup(
            pnl_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tableLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 718, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        pnl_tableLayout.setVerticalGroup(
            pnl_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_tableLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(533, 533, 533)
                        .addComponent(jButton1))
                    .addComponent(pnl_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(16, 16, 16)
                .addComponent(pnl_table, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Dashboard_guru().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl_rekapMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_rekapMouseClicked
        int row = tbl_rekap.getSelectedRow();
        if (row != -1) {
            String idAbsensi = tbl_rekap.getValueAt(row, 0).toString();

            detail_absensi detail = new detail_absensi(); 

            detail.id_terpilih = idAbsensi;
            detail.loadDataDetail();

            detail.setVisible(true);
        }
    }//GEN-LAST:event_tbl_rekapMouseClicked

    private void loadDataRekap() {
        DefaultTableModel model = (DefaultTableModel) tbl_rekap.getModel();
        model.setRowCount(0);

        String sql = "SELECT a.id_absensi, a.tanggal, a.pertemuan_ke, " +
                     "SUM(CASE WHEN d.status = 'Hadir' THEN 1 ELSE 0 END) as hadir, " +
                     "SUM(CASE WHEN d.status = 'Sakit' THEN 1 ELSE 0 END) as sakit, " +
                     "SUM(CASE WHEN d.status = 'Izin' THEN 1 ELSE 0 END) as izin, " +
                     "SUM(CASE WHEN d.status = 'Alpa' THEN 1 ELSE 0 END) as alpa " +
                     "FROM absensi a " +
                     "JOIN detail_absensi d ON a.id_absensi = d.id_absensi " +
                     "GROUP BY a.id_absensi ORDER BY a.tanggal DESC";

        try (Connection conn = koneksi.getKoneksi();
             Statement st = conn.createStatement();
             ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {
                // Gabungkan status jadi satu string ringkasan atau biarkan terpisah kolomnya
                String ringkasan = "H: " + rs.getInt("hadir") + " S: " + rs.getInt("sakit") + 
                                   " I: " + rs.getInt("izin") + " A: " + rs.getInt("alpa");

                model.addRow(new Object[]{
                    rs.getString("id_absensi"), // Hidden column jika perlu
                    rs.getString("tanggal"),
                    "Pertemuan Ke-" + rs.getString("pertemuan_ke"),
                    ringkasan,
                    "Lihat Detail" // Ini nanti dideteksi di mouse click
                });
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal load rekap: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Rekap_absensi().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnl_table;
    private javax.swing.JTable tbl_rekap;
    // End of variables declaration//GEN-END:variables
}
