/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package E_4BSEN;

import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.DocumentFilter;
import javax.swing.JOptionPane;
import java.sql.*;

/**
 *
 * @author DELL
 */
public class tambah_siswa_baru extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(tambah_siswa_baru.class.getName());

    /**
     * Creates new form tambah_siswa_baru
     */
    public tambah_siswa_baru() {
        initComponents();
        
            tf_nis.putClientProperty("JTextField.placeholderText", "Masukkan NIS");
            tf_namalengkap.putClientProperty("JTextField.placeholderText", "Masukkan Nama Lengkap Siswa");
            tf_alamat.putClientProperty("JTextField.placeholderText", "Masukkan Alamat Siswa");
        
            ((AbstractDocument) tf_nis.getDocument()).setDocumentFilter(new DocumentFilter() {
                @Override
                public void insertString(FilterBypass fb, int offset, String string, AttributeSet attr) throws BadLocationException {
                    if (string.matches("\\d+")) { // Hanya izinkan digit (0-9)
                        super.insertString(fb, offset, string, attr);
                    }
                }

                @Override
                public void replace(FilterBypass fb, int offset, int length, String text, AttributeSet attrs) throws BadLocationException {
                    if (text.matches("\\d+")) { // Hanya izinkan digit (0-9)
                        super.replace(fb, offset, length, text, attrs);
                    }
                }
            });
    }
    
        public void siapkanEdit(String nis, String nama, String jk, String kelas, String alamat) {
            tf_nis.setText(nis);
            tf_nis.setEditable(false);
            tf_namalengkap.setText(nama);
            cb_jeniskelamin.setSelectedItem(jk);
            cb_kelas.setSelectedItem(kelas);
            tf_alamat.setText(alamat);

            lbl_judul.setText("Edit Data Siswa");
            btn_simpan.setText("Update");
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbl_judul = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_nis = new javax.swing.JTextField();
        tf_alamat = new javax.swing.JTextField();
        cb_jeniskelamin = new javax.swing.JComboBox<>();
        cb_kelas = new javax.swing.JComboBox<>();
        tf_namalengkap = new javax.swing.JTextField();
        batal = new javax.swing.JButton();
        btn_simpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(26, 135, 84));

        lbl_judul.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lbl_judul.setForeground(new java.awt.Color(255, 255, 255));
        lbl_judul.setText("Tambah Siswa Baru");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lbl_judul)
                .addContainerGap(214, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lbl_judul)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("NIS");

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel3.setText("Nama Lengkap Siswa");

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel5.setText("Kelas");

        jLabel6.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel6.setText("Alamat");

        tf_nis.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tf_nis.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tf_nisKeyTyped(evt);
            }
        });

        tf_alamat.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        cb_jeniskelamin.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cb_jeniskelamin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        cb_kelas.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cb_kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "XI RPL 1", "XI RPL 2", "XI RPL 3" }));

        tf_namalengkap.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tf_namalengkap.setPreferredSize(new java.awt.Dimension(64, 36));

        batal.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });

        btn_simpan.setBackground(new java.awt.Color(26, 135, 84));
        btn_simpan.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        btn_simpan.setForeground(new java.awt.Color(255, 255, 255));
        btn_simpan.setText("Simpan");
        btn_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(batal)
                        .addGap(18, 18, 18)
                        .addComponent(btn_simpan))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_namalengkap, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                        .addComponent(jLabel4)
                        .addComponent(jLabel5)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(tf_nis)
                        .addComponent(cb_kelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cb_jeniskelamin, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_alamat)
                        .addComponent(jLabel6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_nis, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_namalengkap, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_jeniskelamin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(batal)
                    .addComponent(btn_simpan))
                .addGap(17, 17, 17))
        );

        getContentPane().add(jPanel1, new java.awt.GridBagConstraints());

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_simpanActionPerformed
        String nis = tf_nis.getText();
        String nama = tf_namalengkap.getText();
        String jk = cb_jeniskelamin.getSelectedItem().toString();
        String namaKelas = cb_kelas.getSelectedItem().toString();
        String alamat = tf_alamat.getText();

        // 1. Validasi Input Kosong
        if (nis.isEmpty() || nama.isEmpty() || alamat.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Semua field harus diisi!");
            return;
        }

        try (Connection conn = koneksi.getKoneksi()) {
            // 2. Ambil ID Kelas (Integer) berdasarkan Nama Kelas (String)
            int idKelas = 0;
            String sqlCari = "SELECT id_kelas FROM kelas WHERE nama_kelas = ?";
            PreparedStatement psCari = conn.prepareStatement(sqlCari);
            psCari.setString(1, namaKelas);
            ResultSet rsCari = psCari.executeQuery();

            if (rsCari.next()) {
                idKelas = rsCari.getInt("id_kelas");
            }

            // 3. Tentukan Query (Insert atau Update)
            String sql;
            if (btn_simpan.getText().equals("Simpan")) {
                // Urutan: nama, jk, id_kelas, alamat, nis
                sql = "INSERT INTO siswa (nama_siswa, jenis_kelamin, id_kelas, alamat, nis) VALUES (?, ?, ?, ?, ?)";
            } else {
                // Urutan: nama, jk, id_kelas, alamat, WHERE nis
                sql = "UPDATE siswa SET nama_siswa=?, jenis_kelamin=?, id_kelas=?, alamat=? WHERE nis=?";
            }

            PreparedStatement ps = conn.prepareStatement(sql);
            ps.setString(1, nama);
            ps.setString(2, jk);
            ps.setInt(3, idKelas); // Masukkan angkanya (Integer)
            ps.setString(4, alamat);
            ps.setString(5, nis);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Berhasil Di" + (btn_simpan.getText().equals("Simpan") ? "simpan" : "update") + "!");

            this.dispose(); // Tutup form setelah sukses

        } catch (SQLException e) {
            // Menangani error Duplicate Entry atau kolom tidak ditemukan
            JOptionPane.showMessageDialog(this, "Gagal: " + e.getMessage());
        }
        
        new Data_siswa().setVisible(true);
    }//GEN-LAST:event_btn_simpanActionPerformed

    private void tf_nisKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_nisKeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_tf_nisKeyTyped

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        new Data_siswa().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_batalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new tambah_siswa_baru().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal;
    private javax.swing.JButton btn_simpan;
    private javax.swing.JComboBox<String> cb_jeniskelamin;
    private javax.swing.JComboBox<String> cb_kelas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_judul;
    private javax.swing.JTextField tf_alamat;
    private javax.swing.JTextField tf_namalengkap;
    private javax.swing.JTextField tf_nis;
    // End of variables declaration//GEN-END:variables
}
